spring.application.name=The_Vault
spring.config.import=optional:application-secret.properties

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

server.port=${PORT:8080} 

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

api.security.token.secret=${JWT_SECRET}